{
    "bf16": {
        "enabled": "auto"
    },
    "fp16": {
        "enabled": "auto"
    },
    "optimizer": "auto",
    "scheduler": "auto",
    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 5e8,
        "contiguous_gradients": true
    },
    "gradient_accumulation_steps": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "train_batch_size": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": "auto",
    "wall_clock_breakdown": false
}
